/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> = listOf(
    "alfabet",
    "anekdot",
    "balon",
    "baju",
    "baik",
    "bangku",
    "bantal",
    "bebas",
    "belajar",
    "belanja",
    "bencana",
    "benih",
    "berkemah",
    "berkelana",
    "berlawanan",
    "bermeditasi",
    "bernegosiasi",
    "bersama",
    "berputar",
    "besar",
    "bingkai",
    "biola",
    "buku",
    "bulan",
    "bunga",
    "cepat",
    "ceria",
    "corong",
    "dapur",
    "dinosaurus",
    "dibawah",
    "dunia",
    "es",
    "gajah",
    "gaya",
    "gigi",
    "gigitan",
    "gitar",
    "gunung",
    "gurita",
    "hebat",
    "hewan",
    "hidung",
    "hijau",
    "ikon",
    "iglo",
    "investasi",
    "kaca",
    "kamera",
    "kaleidoskop",
    "kanguru",
    "kamu",
    "kecil",
    "kelas",
    "klasik",
    "keranjang",
    "kopi",
    "koala",
    "kreatif",
    "kucing",
    "kutub",
    "laju",
    "lama",
    "lampu",
    "laut",
    "lelucon",
    "lemon",
    "lezat",
    "lilin",
    "lily",
    "listrik",
    "lukisan",
    "majalah",
    "malam",
    "makan",
    "makan",
    "madu",
    "mahal",
    "majalah",
    "mengangkat",
    "mengapa",
    "mengambil",
    "mengapa",
    "mengikuti",
    "mengundang",
    "mengobrol",
    "melepaskan",
    "melodi",
    "melompat",
    "menari",
    "menit",
    "menyala",
    "menyapa",
    "menyukai",
    "mimpi",
    "mobil",
    "monumen",
    "motor",
    "musik",
    "muncul",
    "nama",
    "nomor",
    "paket",
    "pemandangan",
    "pelayaran",
    "pesawat",
    "pesanan",
    "piknik",
    "pohon",
    "podcast",
    "pizza",
    "presentasi",
    "rahai",
    "rahasia",
    "ratusan",
    "rapi",
    "resep",
    "restoran",
    "ruang",
    "kelas",
    "rubah",
    "saudara",
    "selalu",
    "semua",
    "semangat",
    "senja",
    "seram",
    "seratus",
    "sering",
    "setengah",
    "siang hari",
    "silahkan",
    "sini",
    "tas",
    "taksi",
    "tangan",
    "tertawa",
    "terbaik",
    "terjadi",
    "terbuka",
    "terdiri",
    "terjun",
    "terlambat",
    "timur",
    "toilet",
    "tolong",
    "turis",
    "unicorn",
    "unik",
    "utara",
    "vas",
    "video",
    "visi",
    "volume",
    "walrus",
    "wayang",
    "x-ray",
    "xylophone",
    "yoga",
    "yogurt",
    "yoyo",
    "zamrud",
    "zebra",
    "zigzag",
    "zona",
    "zoologi"
)
